name: deploy to heroku
on:
  push:
    branches:
      - master
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: install dependencies
        run: npm install --prefix=./client

      - name: react build
        run: npm run build --prefix=./client

      - name: sync files
        run: mv ./client/build ./server/www

      - name: move to root
        run: mv ./server/* ./

      - name: remove unused files
        run: rm -r ./client ./server ./.github

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: "zakariyaghanai@gmail.com"
          procfile: 'web: node main.js'