name: Github Pages Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: Install dependencies
        run: npm install --prefix=./client

      - name: React Build
        run: npm run build --prefix=./client

      - name: Deploy To Guthub Pages
        run: |
          cd ./client/build
          ls
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          git init
          git add -A
          git commit -m 'New Deployment'
          git push -f https://${user_name}:${github_token}@github.com/${repository}.git master:gh-pages
        env:
          user_name: 'zakaryaghanai'
          user_email: 'zakariyaghanai@gmail.com'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}